### ISSUE TITLE
Readme for Ros2 Humble

### ISSUE THREAD

**Issue by PranavShevkar** [naturerobots/mesh_navigation#53]
From the commits it appears that the ros2 version works but I'm still struggling to build it. It would be nice if someone updates the readme for the humble branch.

**Comment by Cakem1x** [comment]
Hi there, thanks for your interest!
We are in the process of migrating mesh navigation and related repositories to ROS2. We are almost there!
At the moment, however, a few components are not yet publicly available for ROS2, so building `mesh_navigation` is not possible. We're working hard to change this asap!

**Comment by Cakem1x** [comment]
I'd be happy to add a few lines in the readme on how to get all deps and build `mesh_navigation`, good idea.

**Comment by PranavShevkar** [comment]
Thank you so much

**Comment by iliabaranov** [comment]
Might be a good idea to remove dependency on move base flex, and move to the more actively developed NAV2?

**Comment by Cakem1x** [comment]
Move base flex is now available for ROS 2 humble: https://github.com/naturerobots/move_base_flex/tree/humble
I created a [PR](https://github.com/naturerobots/mesh_navigation/pull/65) for updating the readme with build instructions. Have a look!

**Comment by fmrico** [comment]
> I am hopeful that their [NavMap](https://github.com/EasyNavigation/NavMap/) will be compatible with MeshNavigation.

What is your idea here? Replace MeshMap with NavMap, or integrate inside MeshMap the core structure of NavMap?
